# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test111():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_111(self):
        self.driver.get("https://music.taihe.com/")
        self.driver.maximize_window()
        ActionChains(self.driver).move_to_element(self.driver.find_element_by_css_selector('.tracklist-box.clearfix div:nth-child(test_qiyeweixin)')).perform()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".tracklist-box.clearfix div:nth-child(test_qiyeweixin)").click()
        time.sleep(5)